

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: react_client

    restart: unless-stopped

    working_dir: /app

    ports:
      - "5173:5173"

    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: node_server

    restart: unless-stopped

    working_dir: /app

    ports:
      - "5000:${SERVER_PORT}"

    environment:
      - PORT=${SERVER_PORT:?SERVER_PORT is not set}
      - SALT_ROUNDS=${SALT_ROUNDS:?SALT_ROUNDS is not set}
      - JWT_SECRET=${JWT_SECRET:?JWT_SECRET is not set}
      - JWT_EXPIRES=${JWT_EXPIRES:?JWT_EXPIRES is not set}
      - REFRESH_TOKEN_EXPIRES=${REFRESH_TOKEN_EXPIRES:?REFRESH_TOKEN_EXPIRES is not set}
      - DATABASE_NAME=${DATABASE_NAME:?DATABASE_NAME is not set}
      - DATABASE_USER=${DATABASE_USER:?DATABASE_USER is not set}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?DATABASE_PASSWORD is not set}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?DATABASE_PASSWORD is not set}
      - DATABASE_HOST=${DATABASE_HOST:?DATABASE_HOST is not set}
      - DATABASE_PORT=${DATABASE_PORT:?DATABASE_PORT is not set}

    env_file:
      - .env

    depends_on:
      - postgres

    networks:
      - app_network


  postgres:
    image: postgres:16-alpine

    container_name: postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: ${DATABASE_NAME:?DATABASE_NAME is not set}
      POSTGRES_USER: ${DATABASE_USER:?DATABASE_USER is not set}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD is not set}


    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app_network


  gateway:
    image: nginx:stable-alpine

    container_name: gateway

    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/conf.d:/etc/nginx/conf.d

    depends_on:
      - client
      - server

    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: